"""Starter firmware generation from the hardware map.

Scope, deliberately narrow (set by firmware-engineer feedback: "only for
basic application, follow schematic"): a pin-definitions header and a demo
sketch skeleton for the board's identified controller -- a grounded
starting point, never production firmware. The model receives ONLY the
hardware map (verified connectivity + identified parts + datasheet facts),
must use only pins that exist in it, and must mark anything it can't know
as a TODO rather than inventing it. Every generated file carries a header
saying what it is and where it came from.
"""

from __future__ import annotations

import json
import os

from openai import OpenAI
from pydantic import BaseModel, Field

from schemantic.supervisor.core import Supervisor

MODEL = os.getenv("SCHEMANTIC_FIRMWARE_MODEL", "gpt-4.1")
_EST_COST_USD = 0.04
MAX_FILES = 6


class GeneratedFile(BaseModel):
    path: str = Field(description="Relative file path, e.g. 'include/board_pins.h'")
    content: str


class StarterFirmware(BaseModel):
    reasoning: str = Field(
        description="Which controller and framework were chosen and why, which buses/"
        "peripherals from the hardware map the demo exercises, and what was left as TODO "
        "because the map doesn't carry it."
    )
    framework: str = Field(description="e.g. 'Arduino (ESP32 core)' or 'ESP-IDF'")
    files: list[GeneratedFile] = Field(
        description=f"Up to {MAX_FILES} files: a pin-definitions header derived strictly "
        "from the hardware map, and a minimal demo application (e.g. init buses, probe "
        "the I2C devices the map lists, blink/log). Nothing beyond basic bring-up."
    )


_SYSTEM = """You generate STARTER firmware from a hardware map extracted from a board's schematic.

Hard rules:
- Use ONLY pins, nets, buses, and parts present in the provided hardware map. If a needed
  detail (an I2C address, a baud rate, a polarity) is not in the map or its datasheet facts,
  write a clearly marked TODO comment instead of guessing.
- Pin numbers in the map are the CONTROLLER's package pin identifiers; where the mapping to
  firmware GPIO numbers is not derivable from net aliases (e.g. a net named IO33 clearly maps
  to GPIO33), leave a TODO.
- Scope: pin definitions + bus init + a minimal demo (probe/log). No drivers, no RTOS setup,
  no production claims.
- Every file starts with a comment: generated by Schemantic from <board>; a starting point,
  verify against the schematic and datasheets before flashing."""


def generate_starter(
    hw_map: dict, client: OpenAI, supervisor: Supervisor
) -> StarterFirmware:
    compact = {
        "board": hw_map["board"],
        "controllers": hw_map["controllers"],
        "buses": hw_map["buses"],
        "power_rails": hw_map["power_rails"][:6],
        "identified_parts": hw_map["identified_parts"],
    }
    with supervisor.stage("firmware_starter"):
        response = client.responses.parse(
            model=MODEL,
            input=[
                {"role": "system", "content": _SYSTEM},
                {
                    "role": "user",
                    "content": "Hardware map:\n" + json.dumps(compact, indent=1)[:60000],
                },
            ],
            text_format=StarterFirmware,
        )
        supervisor.spend("firmware_starter", _EST_COST_USD)
    result = response.output_parsed
    result.files = result.files[:MAX_FILES]
    return result
